// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsGM1Wr20TP1CHHVpsh5eJivoauuNoOoo',
    appId: '1:942625397200:web:7eb966b72aa06f7abac1d5',
    messagingSenderId: '942625397200',
    projectId: 'homecheffoodlink',
    authDomain: 'homecheffoodlink.firebaseapp.com',
    storageBucket: 'homecheffoodlink.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJxsunD61sOiUynoNrT_A_7BRJY0Gis_8',
    appId: '1:942625397200:android:e7bc7d03643e7adcbac1d5',
    messagingSenderId: '942625397200',
    projectId: 'homecheffoodlink',
    storageBucket: 'homecheffoodlink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYbSZkWHrALWpmOtM1uUZh_7ZqbaI9-1Q',
    appId: '1:942625397200:ios:7437a5a5eae102d4bac1d5',
    messagingSenderId: '942625397200',
    projectId: 'homecheffoodlink',
    storageBucket: 'homecheffoodlink.appspot.com',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYbSZkWHrALWpmOtM1uUZh_7ZqbaI9-1Q',
    appId: '1:942625397200:ios:7437a5a5eae102d4bac1d5',
    messagingSenderId: '942625397200',
    projectId: 'homecheffoodlink',
    storageBucket: 'homecheffoodlink.appspot.com',
    iosBundleId: 'com.example.uberApp',
  );
}
